import { randomUUID } from "node:crypto";
import Link from "next/link";
import { notFound } from "next/navigation";

import { archiveProductAction, reactivateProductAction, updateProductAction } from "@/app/products/actions";
import { getProductMasterData } from "@/lib/supabase-rest";

export const dynamic = "force-dynamic";
type SearchParams = { success?: string; error?: string };
const formatter = new Intl.NumberFormat("id-ID");
function quantity(value: number) { return formatter.format(Number(value)); }
function formatDate(value: string) { return new Intl.DateTimeFormat("id-ID", { timeZone: "Asia/Jakarta", dateStyle: "medium", timeStyle: "short", hour12: false }).format(new Date(value)); }
function Message({ params }: { params: SearchParams }) { const text = params.success ?? params.error; return text ? <p role="status" className={`mb-5 rounded-xl border px-4 py-3 text-sm ${params.error ? "border-rose-400/30 bg-rose-400/10 text-rose-100" : "border-emerald-400/30 bg-emerald-400/10 text-emerald-100"}`}>{text}</p> : null; }

export default async function ProductDetailPage({ params, searchParams }: { params: Promise<{ productId: string }>; searchParams: Promise<SearchParams> }) {
  const [{ productId }, query] = await Promise.all([params, searchParams]);
  let data;
  try { data = await getProductMasterData(); } catch { return <main className="min-h-screen px-5 py-12 text-slate-100"><section className="panel-card mx-auto max-w-3xl"><h1 className="section-title">Produk gagal dimuat.</h1><p className="mt-3 text-slate-300">Sesi Admin diperlukan atau koneksi aplikasi perlu diperiksa.</p></section></main>; }
  const product = data.products.find((row) => row.product_id === productId);
  if (!product) notFound();
  const audits = data.audits.filter((audit) => audit.product_id === product.product_id);
  const lockedSku = product.has_authoritative_history;
  return <main className="mx-auto w-full max-w-6xl px-5 py-8 text-slate-100"><Link className="nav-link inline-flex" href="/products">← Kembali ke Produk</Link><header className="mt-5 flex flex-wrap items-start justify-between gap-4"><div><p className="section-kicker">Master Data / Produk</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{product.name}</h1><p className="mt-1 font-mono text-sm text-emerald-300">{product.sku}</p></div><span className={product.is_active ? "status-pill status-success" : "status-pill status-warning"}>{product.is_active ? "AKTIF" : "DIARSIPKAN"}</span></header><Message params={query} />
  <section className="mt-6 grid gap-4 md:grid-cols-3"><div className="metric-card"><p className="text-xs text-slate-400">Sellable</p><p className="mt-1 text-2xl font-semibold">{quantity(product.sellable_qty)}</p></div><div className="metric-card"><p className="text-xs text-slate-400">Quarantine / Damaged</p><p className="mt-1 text-2xl font-semibold">{quantity(product.quarantine_qty)} / {quantity(product.damaged_qty)}</p></div><div className="metric-card"><p className="text-xs text-slate-400">Reserved / Available</p><p className="mt-1 text-2xl font-semibold">{quantity(product.reserved_qty)} / {quantity(product.available_qty)}</p></div></section>
  <section className="panel-card mt-6"><p className="section-kicker">Edit Produk</p><h2 className="section-title">Identitas master</h2>{lockedSku && <p className="mt-3 rounded-xl border border-amber-400/25 bg-amber-400/10 px-4 py-3 text-sm text-amber-100">SKU dikunci karena Produk sudah dipakai transaksi. Nama dan deskripsi tetap dapat diperbarui tanpa mengubah snapshot ledger lama.</p>}<form action={updateProductAction} className="form-grid mt-5"><input type="hidden" name="intentId" value={randomUUID()} /><input type="hidden" name="productId" value={product.product_id} /><input type="hidden" name="rowVersion" value={product.row_version} /><label className="field-label">SKU{lockedSku ? <><input type="hidden" name="sku" value={product.sku} /><input value={product.sku} disabled readOnly aria-describedby="sku-lock-reason" /></> : <input required name="sku" defaultValue={product.sku} />}</label><label className="field-label">Nama Produk<input required name="name" defaultValue={product.name} /></label><label className="field-label">Satuan<input value="UNIT" readOnly /></label><label className="field-label">Deskripsi<textarea name="description" rows={3} defaultValue={product.description ?? ""} /></label><label className="field-label sm:col-span-2">Catatan audit<textarea name="note" rows={2} placeholder="Opsional; jelaskan perubahan" /></label>{lockedSku && <p id="sku-lock-reason" className="text-xs text-amber-200 sm:col-span-2">SKU telah memiliki histori authoritative.</p>}<div className="sm:col-span-2"><button className="primary-button" type="submit">Simpan perubahan</button></div></form></section>
  <section className="panel-card mt-6"><p className="section-kicker">Status Produk</p><h2 className="section-title">{product.is_active ? "Arsipkan Produk" : "Aktifkan kembali Produk"}</h2><p className="mt-3 text-sm leading-6 text-slate-400">{product.is_active ? "Pengarsipan menghentikan pemakaian Produk pada transaksi baru. Histori, audit, dan snapshot lama tidak dihapus." : "Reaktivasi hanya dapat dilakukan bila identitas SKU tidak berbenturan dengan Produk aktif lain."}</p><form action={product.is_active ? archiveProductAction : reactivateProductAction} className="mt-5 grid gap-3"><input type="hidden" name="intentId" value={randomUUID()} /><input type="hidden" name="productId" value={product.product_id} /><input type="hidden" name="rowVersion" value={product.row_version} /><label className="field-label">Alasan / catatan<textarea name="reason" rows={2} placeholder="Direkomendasikan untuk audit" /></label><label className="flex items-center gap-2 text-sm text-slate-200"><input name="confirmation" type="checkbox" /> Saya memahami perubahan status ini tidak menghapus histori.</label><div><button className="primary-button" type="submit">{product.is_active ? "Konfirmasi arsip Produk" : "Konfirmasi aktifkan Produk"}</button></div></form></section>
  <section className="panel-card mt-6"><p className="section-kicker">Konteks master</p><div className="mt-4 grid gap-3 text-sm text-slate-300 sm:grid-cols-2"><p>Histori authoritative: <strong>{product.has_authoritative_history ? "Ada" : "Belum ada"}</strong></p><p>Jumlah Batch: <strong>{quantity(product.batch_count)}</strong></p><p>Referensi listing: <strong>{quantity(product.listing_reference_count)}</strong></p><p>Ledger sequence terakhir: <strong>{quantity(product.last_ledger_seq)}</strong></p><p>Dibuat: <strong>{formatDate(product.created_at)}</strong></p><p>Diperbarui: <strong>{formatDate(product.updated_at)}</strong></p></div></section>
  <section className="panel-card mt-6"><p className="section-kicker">Audit Produk</p><h2 className="section-title">Jejak perubahan</h2>{audits.length === 0 ? <p className="mt-4 text-sm text-slate-400">Belum ada audit Produk.</p> : <div className="mt-5 overflow-x-auto"><table><thead><tr><th>Waktu</th><th>Aksi</th><th>Actor</th><th>Alasan / catatan</th><th>Command</th></tr></thead><tbody>{audits.map((audit) => <tr key={audit.audit_id}><td>{formatDate(audit.occurred_at)}</td><td>{audit.action_code}</td><td>{audit.actor_display_name ?? audit.process_name ?? "Proses tepercaya"}</td><td>{audit.reason ?? audit.note ?? "-"}</td><td>{audit.command_scope}</td></tr>)}</tbody></table></div>}</section></main>;
}