const SAFE_UPLOAD_ERROR_CODES = new Set([
  "AUTH_SESSION_REQUIRED",
  "CSV_FILE_REQUIRED",
  "CSV_IMPORT_UPLOAD_FAILED",
  "DUPLICATE_FILE",
  "FILE_TOO_LARGE",
  "IDEMPOTENCY_KEY_REUSED",
  "IMPORT_ADMIN_REQUIRED",
  "IMPORT_FILE_TOO_LARGE",
  "IMPORT_INVALID_COMMAND_KEY",
  "IMPORT_INVALID_FILE_HASH",
  "IMPORT_INVALID_FILE_NAME",
  "IMPORT_INVALID_MIME",
  "IMPORT_INVALID_REQUEST_HASH",
  "INVALID_EXTENSION",
  "INVALID_MIME",
  "INVALID_UTF8",
  "BINARY_CONTENT",
  "MALFORMED_CSV",
  "UNKNOWN_HEADER",
  "DUPLICATE_HEADER",
  "MISSING_HEADER",
  "UNEQUAL_COLUMNS",
  "UNSUPPORTED_SCHEMA_VERSION",
  "UNSUPPORTED_EVENT_TYPE",
  "INVALID_SOURCE_STATUS",
  "INVALID_TIMESTAMP",
  "RECEIVED_BEFORE_OCCURRED",
  "INVALID_QUANTITY",
  "FIELD_TOO_LONG",
  "ROW_LIMIT_EXCEEDED",
  "EVENT_LINE_LIMIT_EXCEEDED",
  "EXPANDED_LINE_LIMIT_EXCEEDED",
  "DUPLICATE_SOURCE_LINE",
  "EVENT_IDENTITY_CONFLICT",
  "CSV_IMPORT_VALIDATION_FAILED",
]);

const SAFE_COMMIT_ERROR_CODES = new Set([
  "CSV_IMPORT_COMMIT_FAILED",
  "CSV_IMPORT_COMMIT_CONFIRMATION_REQUIRED",
  "CSV_IMPORT_COMMIT_KEY_INVALID",
  "CSV_IMPORT_COMMIT_JOB_REQUIRED",
  "CSV_IMPORT_COMMIT_STATE_INVALID",
  "CSV_IMPORT_COMMIT_IN_PROGRESS",
  "CSV_IMPORT_COMMIT_FAILED_REPLAY",
  "CSV_IMPORT_ALREADY_COMPLETED",
  "CSV_IMPORT_BLOCKING_ROWS",
  "CSV_IMPORT_NO_ROWS",
  "CSV_IMPORT_JOB_NOT_FOUND",
  "CSV_EXTERNAL_EVENT_CONFLICT",
  "CSV_EXTERNAL_EVENT_ALREADY_EXISTS",
  "IDEMPOTENCY_KEY_REUSED",
]);

function candidateCode(value: unknown) {
  const message = typeof value === "string" ? value : value instanceof Error ? value.message : "";
  return message.split("|")[0]?.trim() ?? "";
}

export function safeMarketplaceCsvUploadErrorCode(value: unknown) {
  const candidate = candidateCode(value);
  return SAFE_UPLOAD_ERROR_CODES.has(candidate) ? candidate : "CSV_IMPORT_UPLOAD_FAILED";
}

export function safeMarketplaceCsvCommitErrorCode(value: unknown) {
  const candidate = candidateCode(value);
  return SAFE_COMMIT_ERROR_CODES.has(candidate) ? candidate : "CSV_IMPORT_COMMIT_FAILED";
}
