begin;

create or replace function notification.evaluate_tiktok_claim_deadlines(p_organization_id uuid,p_idempotency_key text,p_observed_at timestamptz default clock_timestamp(),p_process_name text default 'notification.evaluate_tiktok_claim_deadlines') returns jsonb language plpgsql security definer set search_path = pg_catalog, notification, operations, app, extensions as $$
declare v_key text:=btrim(coalesce(p_idempotency_key,'')); v_process text:=nullif(btrim(coalesce(p_process_name,'')), ''); v_rule notification.rules%rowtype; v_missing_rule uuid; v_existing notification.rule_runs%rowtype; v_run uuid; v_claim record; v_stage text; v_severity text; v_result jsonb; v_created integer:=0; v_updated integer:=0; v_resolved integer:=0; v_skipped integer:=0; v_evaluated integer:=0;
begin
  if p_organization_id is null or v_key='' or length(v_key)>200 or p_observed_at is null or v_process is null then raise exception using errcode='P0001',message='CLAIM_NOTIFICATION_REQUEST_INVALID'; end if;
  if not exists(select 1 from app.organizations where id=p_organization_id and is_active) then raise exception using errcode='P0001',message='NOTIFICATION_ORGANIZATION_NOT_FOUND'; end if;
  perform pg_advisory_xact_lock(hashtextextended(p_organization_id::text||':NOTIFICATION_EVALUATOR:TIKTOK_CLAIM',0));
  select * into v_existing from notification.rule_runs where organization_id=p_organization_id and rule_code_snapshot='CLAIM_DEADLINE' and idempotency_key=v_key for update;
  if found then return jsonb_build_object('action','REPLAYED','ruleRunId',v_existing.id,'status',v_existing.status_code,'evaluatedCount',v_existing.evaluated_count,'stockEffectCode','NONE'); end if;
  perform notification.ensure_tiktok_claim_rule(p_organization_id,'CLAIM_DEADLINE',p_observed_at); v_missing_rule:=notification.ensure_tiktok_claim_rule(p_organization_id,'CLAIM_BASIS_MISSING',p_observed_at);
  select * into strict v_rule from notification.rules where organization_id=p_organization_id and code='CLAIM_DEADLINE' and is_active and effective_from<=p_observed_at and (effective_to is null or effective_to>p_observed_at) order by effective_from desc, created_at desc limit 1;
  insert into notification.rule_runs(organization_id,rule_id,rule_code_snapshot,rule_version_snapshot,trigger_type_code,idempotency_key,status_code,started_at,evaluated_count,created_count,updated_count,resolved_count,skipped_count,error_count,summary,error_detail,correlation_id,process_name) values(p_organization_id,v_rule.id,v_rule.code,v_rule.version,'SCHEDULED',v_key,'STARTED',clock_timestamp(),0,0,0,0,0,0,'{}','{}',gen_random_uuid(),v_process) returning id into v_run;
  for v_claim in select * from operations.return_claims where organization_id=p_organization_id order by id loop
    v_evaluated:=v_evaluated+1;
    if v_claim.status_code in ('SUBMITTED','RESOLVED','CANCELLED') then
      for v_result in select notification.resolve_notification(p_organization_id,n.id,'CLAIM_LIFECYCLE_COMPLETED',jsonb_build_object('claimId',v_claim.id,'status',v_claim.status_code,'ruleRunId',v_run,'stockEffectCode','NONE'),p_observed_at,gen_random_uuid(),'Claim lifecycle no longer needs deadline reminder.',null,v_process) as value from notification.notifications n where n.organization_id=p_organization_id and n.entity_type_code='RETURN_CLAIM' and n.entity_id=v_claim.id and n.rule_code_snapshot='CLAIM_DEADLINE' and n.lifecycle_status_code in ('OPEN','ACKNOWLEDGED') loop v_resolved:=v_resolved+1; end loop;
      for v_result in select notification.resolve_notification(p_organization_id,n.id,'CLAIM_BASIS_VALID_OR_CANCELLED',jsonb_build_object('claimId',v_claim.id,'status',v_claim.status_code,'ruleRunId',v_run,'stockEffectCode','NONE'),p_observed_at,gen_random_uuid(),'Claim basis exception cleared by lifecycle.',null,v_process) as value from notification.notifications n where n.organization_id=p_organization_id and n.entity_type_code='RETURN_CLAIM' and n.entity_id=v_claim.id and n.rule_code_snapshot='CLAIM_BASIS_MISSING' and n.lifecycle_status_code in ('OPEN','ACKNOWLEDGED') loop v_resolved:=v_resolved+1; end loop;
    elsif v_claim.claim_basis_at is null or v_claim.deadline_at is null then
      v_result:=notification.upsert_active_notification(p_organization_id,v_missing_rule,v_claim.id,'CLAIM_BASIS_MISSING:'||p_organization_id||':'||v_claim.id,'BASIS_MISSING','HIGH','Basis klaim TikTok tidak tersedia','Deadline klaim tidak dapat dievaluasi tanpa basis retur kanonis.','/returns?claimId='||v_claim.id,v_claim.created_at,p_observed_at,null,jsonb_build_object('claimId',v_claim.id,'ruleRunId',v_run,'stockEffectCode','NONE'),'ESCALATED',gen_random_uuid(),null,v_process); if v_result->>'action'='CREATED' then v_created:=v_created+1; else v_updated:=v_updated+1; end if;
    else
      for v_result in select notification.resolve_notification(p_organization_id,n.id,'CLAIM_BASIS_VALID',jsonb_build_object('claimId',v_claim.id,'ruleRunId',v_run,'stockEffectCode','NONE'),p_observed_at,gen_random_uuid(),'Claim basis is valid.',null,v_process) as value from notification.notifications n where n.organization_id=p_organization_id and n.entity_type_code='RETURN_CLAIM' and n.entity_id=v_claim.id and n.rule_code_snapshot='CLAIM_BASIS_MISSING' and n.lifecycle_status_code in ('OPEN','ACKNOWLEDGED') loop v_resolved:=v_resolved+1; end loop;
      if v_claim.status_code='EXPIRED' then v_stage:='OVERDUE'; elsif p_observed_at>v_claim.deadline_at then v_stage:='OVERDUE'; elsif p_observed_at>=v_claim.deadline_at then v_stage:='DUE_TODAY'; elsif p_observed_at>=v_claim.deadline_at-interval '1 day' then v_stage:='D1'; elsif p_observed_at>=v_claim.deadline_at-interval '3 days' then v_stage:='D3'; elsif p_observed_at>=v_claim.deadline_at-interval '7 days' then v_stage:='D7'; elsif p_observed_at>=v_claim.deadline_at-interval '14 days' then v_stage:='D14'; else v_stage:=null; end if;
      if v_stage is null then v_skipped:=v_skipped+1; else v_severity:=case when v_stage='OVERDUE' then 'CRITICAL' when v_stage in ('DUE_TODAY','D1') then 'HIGH' else 'WARNING' end; v_result:=notification.upsert_active_notification(p_organization_id,v_rule.id,v_claim.id,'CLAIM_DEADLINE:'||p_organization_id||':'||v_claim.id,v_stage,v_severity,'Deadline klaim TikTok','Tindak lanjuti claim berdasarkan deadline tersimpan.','/returns?claimId='||v_claim.id,v_claim.claim_basis_at,p_observed_at,v_claim.deadline_at,jsonb_build_object('claimId',v_claim.id,'deadlineAt',v_claim.deadline_at,'ruleRunId',v_run,'stockEffectCode','NONE'),case when not exists(select 1 from notification.notifications n where n.organization_id=p_organization_id and n.entity_type_code='RETURN_CLAIM' and n.entity_id=v_claim.id and n.rule_code_snapshot='CLAIM_DEADLINE' and n.lifecycle_status_code in ('OPEN','ACKNOWLEDGED')) or exists(select 1 from notification.notifications n where n.organization_id=p_organization_id and n.entity_type_code='RETURN_CLAIM' and n.entity_id=v_claim.id and n.rule_code_snapshot='CLAIM_DEADLINE' and n.lifecycle_status_code in ('OPEN','ACKNOWLEDGED') and n.stage_code is distinct from v_stage) then 'ESCALATED' else 'UNCHANGED' end,gen_random_uuid(),null,v_process); if v_result->>'action'='CREATED' then v_created:=v_created+1; else v_updated:=v_updated+1; end if; end if;
    end if;
  end loop;
  update notification.rule_runs set status_code='SUCCEEDED',completed_at=clock_timestamp(),evaluated_count=v_evaluated,created_count=v_created,updated_count=v_updated,resolved_count=v_resolved,skipped_count=v_skipped,summary=jsonb_build_object('schemaVersion',1,'ruleRunId',v_run,'observedAt',p_observed_at,'stockEffectCode','NONE') where id=v_run;
  return jsonb_build_object('action','COMPLETED','ruleRunId',v_run,'status','SUCCEEDED','evaluatedCount',v_evaluated,'createdCount',v_created,'updatedCount',v_updated,'resolvedCount',v_resolved,'stockEffectCode','NONE');
end $$;
revoke all on function notification.evaluate_tiktok_claim_deadlines(uuid,text,timestamptz,text) from public,anon,authenticated;
grant execute on function notification.evaluate_tiktok_claim_deadlines(uuid,text,timestamptz,text) to service_role;
commit;
